# basic options
title: te amo laila
author: jaime dorantes
email: your-email@domain.com
description: A wonderful site
twitter_username: jadp
github_username:  8fenixOrbe8

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
